#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

[[ -s "${ZDOTDIR:-$HOME}/.rvm/scripts/rvm" ]] && source "${ZDOTDIR:-$HOME}/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

ln -fs "$(nvm which default)" /usr/local/bin/node
