#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# http://rvm.io/integration/zsh
# __rvm_project_rvmrc

export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# Customize to your needs...
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias cg="coffeegulp"
